# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
---
project_name: vetr-collector
env_files:
  github_token: ~/.github.com.token
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - rm -rf dist
    - go mod download
    - go test ./...
    - python make_script.py
builds:
  - id: collector
    binary: collector
    main: ./cmd/collector
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - id: collector
    format: zip
    files:
      - README.md
      - LICENSE
      - vetr-collector.sh
    name_template: 'vetr-collector_{{ .Version }}_{{ .Os }}'
    replacements:
      darwin: MacOS
      windows: Windows
      linux: Linux
      amd64: 64-bit

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
